### ISSUE TITLE
addition of  CONTRIBUTING.md file

### ISSUE THREAD

**Issue by shash369** [cocomantis/Hacktoberfest2024#1]
Hello,

according to Hacktoberfest guidelines Add a CONTRIBUTING.md file with contribution guidelines to your repository is necessary so

I would like to contribute to the Hacktoberfest 2024 initiative by adding a CONTRIBUTING.md file to the repository. This file will outline the contribution guidelines for potential contributors, ensuring a smooth and organized contribution process.

Please assign me this task under the Hacktoberfest 2024 label.

Thank you!

**Comment by cocomantis** [comment]
Sure please feel free to add the file under in the repo!

**Comment by cocomantis** [comment]
Thank you!
