### ISSUE TITLE
Add Dark Mode and User Authentication for Personalized Experience

### ISSUE THREAD

**Issue by syedmaazsaeed** [cocomantis/Hacktoberfest2024#13]
@cocomantis 

 Add Dark Mode and User Authentication for Personalized Experience:

 Enhancing user engagement with a dark mode toggle and the ability for users to log in would improve the website's interactivity. Dark 
mode will allow users to switch themes for a better visual experience, while user authentication could offer personalized content.(2nd Issue)

**Comment by cocomantis** [comment]
This is a great suggestion to improve the quality of the website

**Comment by syedmaazsaeed** [comment]
Okay I am starting the project.

**Comment by cocomantis** [comment]
Thank you!

**Comment by cocomantis** [comment]
I think the issue has been resolved now.
