### ISSUE TITLE
Navbar hides the portion of Body

### ISSUE THREAD

**Issue by AustinVarshney** [cocomantis/Hacktoberfest2024#26]
Navbar does not provides the space to the body so that content inside the body will be properly visible.
 
![Issue 2(1) mp4](https://github.com/user-attachments/assets/2f1cae5a-2058-4844-9803-eb0dc91b0eb2)

![Issue 2(2)](https://github.com/user-attachments/assets/6f36a865-9910-4903-87cf-53da7e12bc83)

Please assign me this issue under the hacktoberfest-accepted label.

**Comment by AustinVarshney** [comment]
There is a need of improvements in the forms section. From my point of view, there is no need to make the form. Instead display a   **Generate Name** button for suggesting the Pet Name.

It would be grateful to tell me whether I have to remove the Form and make the _proper designing_ of the **Generate Name** button or not?

**Comment by cocomantis** [comment]
Thank you for the contributions, please do not forget to add your name to the contributors list in the repository, in both files!
