### ISSUE TITLE
Include copyright notice in the footer section of the website.

### ISSUE THREAD

**Issue by im-amanjai** [cocomantis/Hacktoberfest2024#3]
Hello,
This issue proposes adding a copyright notice to the footer section of the website. Including a copyright statement is essential for protecting our intellectual property and clearly indicating ownership.

**Proposed Changes:**
- Add a copyright notice formatted as: "© [Year] [Company/Author Name]. All rights reserved."
- Ensure that the copyright year updates automatically to reflect the current year.

Implementing this change will enhance our site's professionalism and legal compliance.

Additionally, please assign this issue under Hacktoberfest 2024 to encourage contributions. Thank you!

**Comment by cocomantis** [comment]
Sure, please feel free to add the code and improve the quality!
